(program 1.1.0 (case (constr 0 (force (builtin dropList))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin mkCons)) (force (force (builtin sndPair)))
      (force (builtin tailList))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                [(lam g
                    [(lam h
                        [(lam i
                            [(lam j
                                [(lam k
                                    (lam l
                                      [(lam m
                                          [(lam n
                                              [(lam o
                                                  (case [b o] (error) [(lam p
                                                        [(lam q
                                                            [(lam r
                                                                [(lam s
                                                                    (case [b
                                                                        [(builtin unConstrData)
                                                                          r]] [(lam t
                                                                          [(lam u
                                                                              [(lam v
                                                                                  [(lam w
                                                                                      [(lam x
                                                                                          [(lam y
                                                                                              [(lam z
                                                                                                  [(lam aa
                                                                                                      [(lam ab
                                                                                                          [(lam ac
                                                                                                              [(lam ad
                                                                                                                  [(lam ae
                                                                                                                      [(lam af
                                                                                                                          [(lam ag
                                                                                                                              [(lam ah
                                                                                                                                  [(lam ai
                                                                                                                                      [(lam aj
                                                                                                                                          [(lam ak
                                                                                                                                              (case [b
                                                                                                                                                  ak] (error)
                                                                                                                                                (error)
                                                                                                                                                (case [(builtin equalsData)
                                                                                                                                                    [c
                                                                                                                                                      [e
                                                                                                                                                        ak]]
                                                                                                                                                    q] (error)
                                                                                                                                                  (con unit ()))))
                                                                                                                                            [(builtin unConstrData)
                                                                                                                                              [c
                                                                                                                                                [n
                                                                                                                                                  ac]]]])
                                                                                                                                        (case [(builtin equalsInteger)
                                                                                                                                            ag
                                                                                                                                            [(lam al
                                                                                                                                                [k
                                                                                                                                                  [(builtin multiplyInteger)
                                                                                                                                                    [(lam am
                                                                                                                                                        [k
                                                                                                                                                          [am
                                                                                                                                                            x]
                                                                                                                                                          [k
                                                                                                                                                            [am
                                                                                                                                                              [(builtin unIData)
                                                                                                                                                                [c
                                                                                                                                                                  [a
                                                                                                                                                                    (con integer 3)
                                                                                                                                                                    s]]]]
                                                                                                                                                            al]])
                                                                                                                                                      [(builtin subtractInteger)
                                                                                                                                                        [(builtin unIData)
                                                                                                                                                          [c
                                                                                                                                                            [a
                                                                                                                                                              (con integer 4)
                                                                                                                                                              s]]]]]
                                                                                                                                                    [(builtin unIData)
                                                                                                                                                      [c
                                                                                                                                                        [n
                                                                                                                                                          s]]]]
                                                                                                                                                  al])
                                                                                                                                              [(builtin unIData)
                                                                                                                                                [c
                                                                                                                                                  [a
                                                                                                                                                    (con integer 6)
                                                                                                                                                    s]]]]] (error)
                                                                                                                                          (con unit ()))])
                                                                                                                                    (case [(builtin lessThanInteger)
                                                                                                                                        ag
                                                                                                                                        af] (error)
                                                                                                                                      (con unit ()))])
                                                                                                                                (case [(builtin lessThanInteger)
                                                                                                                                    (con integer 0)
                                                                                                                                    ag] (error)
                                                                                                                                  (con unit ()))])
                                                                                                                            [ae
                                                                                                                              [(builtin unValueData)
                                                                                                                                [c
                                                                                                                                  [f
                                                                                                                                    ac]]]]])
                                                                                                                        [ae
                                                                                                                          [(builtin unValueData)
                                                                                                                            [c
                                                                                                                              [f
                                                                                                                                z]]]]])
                                                                                                                    [(builtin lookupCoin)
                                                                                                                      [(builtin unBData)
                                                                                                                        [c
                                                                                                                          ad]]
                                                                                                                      [(builtin unBData)
                                                                                                                        [c
                                                                                                                          [f
                                                                                                                            ad]]]]])
                                                                                                                [e
                                                                                                                  [(builtin unConstrData)
                                                                                                                    [c
                                                                                                                      [f
                                                                                                                        s]]]]])
                                                                                                            (case [(builtin unListData)
                                                                                                                [j
                                                                                                                  [(builtin unListData)
                                                                                                                    [c
                                                                                                                      [n
                                                                                                                        t]]]
                                                                                                                  (lam an
                                                                                                                    [(builtin equalsData)
                                                                                                                      [c
                                                                                                                        [e
                                                                                                                          [(builtin unConstrData)
                                                                                                                            [c
                                                                                                                              [e
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  an]]]]]]
                                                                                                                      aa])]] (lam ao
                                                                                                                (lam ap
                                                                                                                  [e
                                                                                                                    [(builtin unConstrData)
                                                                                                                      ao]]))
                                                                                                              (error))])
                                                                                                        (case [(builtin equalsInteger)
                                                                                                            [(builtin unIData)
                                                                                                              (case (constr 0 [(builtin unListData)
                                                                                                                    [j
                                                                                                                      y
                                                                                                                      (lam aq
                                                                                                                        [(builtin equalsData)
                                                                                                                          [c
                                                                                                                            [e
                                                                                                                              [(builtin unConstrData)
                                                                                                                                [c
                                                                                                                                  [e
                                                                                                                                    [(builtin unConstrData)
                                                                                                                                      [c
                                                                                                                                        [f
                                                                                                                                          [e
                                                                                                                                            [(builtin unConstrData)
                                                                                                                                              aq]]]]]]]]]]
                                                                                                                          aa])]]
                                                                                                                  (con data (I 0))
                                                                                                                  (lam ar
                                                                                                                    [(lam as
                                                                                                                        (lam at
                                                                                                                          [(builtin iData)
                                                                                                                            [(builtin addInteger)
                                                                                                                              as
                                                                                                                              (con integer 1)]]))
                                                                                                                      [(builtin unIData)
                                                                                                                        ar]])) (lam au
                                                                                                                  (lam av
                                                                                                                    (lam aw
                                                                                                                      (case (constr 0 (lam ax
                                                                                                                            (lam ay
                                                                                                                              (lam az
                                                                                                                                (case ay (lam ba
                                                                                                                                    (lam bb
                                                                                                                                      (case (constr 0 ax
                                                                                                                                          bb
                                                                                                                                          [aw
                                                                                                                                            az
                                                                                                                                            ba]) ax)))
                                                                                                                                  az))))
                                                                                                                          au
                                                                                                                          av) (lam bc
                                                                                                                          [bc
                                                                                                                            bc]))))))]
                                                                                                            (con integer 1)] (error)
                                                                                                          (con unit ()))])
                                                                                                    [c
                                                                                                      [e
                                                                                                        [(builtin unConstrData)
                                                                                                          [c
                                                                                                            z]]]]])
                                                                                                [e
                                                                                                  [(builtin unConstrData)
                                                                                                    [c
                                                                                                      [f
                                                                                                        [e
                                                                                                          [(builtin unConstrData)
                                                                                                            [(lam bd
                                                                                                                (case [b
                                                                                                                    bd] [c
                                                                                                                    [e
                                                                                                                      bd]]
                                                                                                                  (error)))
                                                                                                              [(builtin unConstrData)
                                                                                                                [(lam be
                                                                                                                    [(lam bf
                                                                                                                        [bf
                                                                                                                          bf])
                                                                                                                      (lam bg
                                                                                                                        (lam bh
                                                                                                                          (case bh (lam bi
                                                                                                                              (lam bj
                                                                                                                                (case [be
                                                                                                                                    bi] [bg
                                                                                                                                    bg
                                                                                                                                    bj]
                                                                                                                                  [(builtin constrData)
                                                                                                                                    (con integer 0)
                                                                                                                                    [d
                                                                                                                                      bi
                                                                                                                                      (con (list data) [])]])))
                                                                                                                            (con data (Constr 1 [])))))
                                                                                                                      y])
                                                                                                                  [(lam bk
                                                                                                                      (lam bl
                                                                                                                        [(builtin equalsData)
                                                                                                                          [c
                                                                                                                            [e
                                                                                                                              [(builtin unConstrData)
                                                                                                                                bl]]]
                                                                                                                          bk]))
                                                                                                                    [(builtin constrData)
                                                                                                                      (con integer 0)
                                                                                                                      [e
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            p]]]]]]]]]]]]]]])
                                                                                            [(builtin unListData)
                                                                                              [c
                                                                                                t]]])
                                                                                        [(lam bm
                                                                                            (case [b
                                                                                                bm] (con integer 0)
                                                                                              [(builtin unIData)
                                                                                                [c
                                                                                                  [e
                                                                                                    bm]]]
                                                                                              (con integer 0)))
                                                                                          [(builtin unConstrData)
                                                                                            [c
                                                                                              [e
                                                                                                [(builtin unConstrData)
                                                                                                  [c
                                                                                                    v]]]]]]])
                                                                                    (case [i
                                                                                        v
                                                                                        [(builtin unIData)
                                                                                          [c
                                                                                            [a
                                                                                              (con integer 5)
                                                                                              s]]]] (error)
                                                                                      (con unit ()))])
                                                                                [e
                                                                                  [(builtin unConstrData)
                                                                                    [c
                                                                                      [a
                                                                                        (con integer 7)
                                                                                        t]]]]])
                                                                            (case [g
                                                                                t
                                                                                [h
                                                                                  s]] (error)
                                                                              (con unit ()))])
                                                                        [e
                                                                          [(builtin unConstrData)
                                                                            [c
                                                                              m]]]]
                                                                      [(lam bn
                                                                          [(lam bo
                                                                              (case [i
                                                                                  [e
                                                                                    [(builtin unConstrData)
                                                                                      [c
                                                                                        [a
                                                                                          (con integer 7)
                                                                                          bn]]]]
                                                                                  [(builtin unIData)
                                                                                    [c
                                                                                      [a
                                                                                        (con integer 4)
                                                                                        s]]]] (error)
                                                                                (con unit ())))
                                                                            (case [g
                                                                                bn
                                                                                [h
                                                                                  s]] (error)
                                                                              (con unit ()))])
                                                                        [e
                                                                          [(builtin unConstrData)
                                                                            [c
                                                                              m]]]]))
                                                                  [e
                                                                    [(builtin unConstrData)
                                                                      q]]]) [c
                                                                [f m]]])
                                                          [(lam bp
                                                              (case [b bp] [c [e
                                                                    bp]]
                                                                (error)))
                                                            [(builtin unConstrData)
                                                              [c [f p]]]]]) [e
                                                        o]] (error) (error)
                                                    (error) (error)))
                                                [(builtin unConstrData) [c [n
                                                      m]]]]) [a
                                              (con integer 2)]]) [e
                                          [(builtin unConstrData) l]]])) (lam bq
                                    (lam br
                                      [(builtin addInteger) (con integer 1)
                                        [(builtin divideInteger)
                                          [(builtin subtractInteger) bq
                                            (con integer 1)] br]]))]) (lam bs
                                (lam bt
                                  [(lam bu [bu bu]) (lam bv
                                      (lam bw
                                        (case bw (lam bx
                                            (lam by
                                              [(builtin listData) [(lam bz
                                                    (case [bt bx] bz [d bx bz]))
                                                  [(builtin unListData) [bv bv
                                                      by]]]]))
                                          (con data (List []))))) bs]))])
                          (lam ca
                            (lam cb
                              [(lam cc
                                  [(lam cd
                                      (case [b cd] (con bool False) [(lam ce
                                            (case (case [b
                                                  [(builtin unConstrData) [c [f
                                                        cc]]]] (con bool False)
                                                (con bool True)) [(builtin lessThanEqualsInteger)
                                                cb [(builtin unIData) [c ce]]]
                                              [(builtin lessThanInteger) cb
                                                [(builtin unIData) [c ce]]])) [e
                                            cd]] (con bool False)))
                                    [(builtin unConstrData) [c cc]]]) [e
                                  [(builtin unConstrData) [c ca]]]]))]) (lam cf
                        [(lam cg
                            (case [b cg] [(builtin unBData) [c [e cg]]]
                              (error))) [(builtin unConstrData) [c [e
                                [(builtin unConstrData) [c cf]]]]]])]) (lam ch
                    (lam ci
                      [(lam cj
                          (lam ck
                            [(lam cl [cl cl]) (lam cm
                                (lam cn
                                  (case cn (lam co
                                      (lam cp
                                        (case [(builtin equalsData) co ck] [cm
                                            cm cp] (con bool True))))
                                    (con bool False)))) cj]))
                        [(builtin unListData) [c [a (con integer 8) ch]]]
                        [(builtin bData) ci]]))]))))))))