(program 1.1.0 (case (constr 0 (force (builtin dropList))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin mkCons)) (force (force (builtin sndPair)))
      (force (builtin tailList))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                [(lam g
                    [(lam h
                        [(lam i
                            [(lam j
                                [(lam k
                                    [(lam l
                                        [(lam m
                                            [(lam n
                                                [(lam o
                                                    [(lam p
                                                        [(lam q
                                                            [(lam r
                                                                (lam s
                                                                  [(lam t
                                                                      [(lam u
                                                                          [(lam v
                                                                              (case [b
                                                                                  v] (error)
                                                                                [(lam w
                                                                                    [(lam x
                                                                                        [(lam y
                                                                                            [(lam z
                                                                                                [(lam aa
                                                                                                    (case [b
                                                                                                        [(builtin unConstrData)
                                                                                                          [c
                                                                                                            [f
                                                                                                              t]]]] [(lam ab
                                                                                                          [(lam ac
                                                                                                              [(lam ad
                                                                                                                  [(lam ae
                                                                                                                      [(lam af
                                                                                                                          [(lam ag
                                                                                                                              [(lam ah
                                                                                                                                  [(lam ai
                                                                                                                                      [(lam aj
                                                                                                                                          [(lam ak
                                                                                                                                              [(lam al
                                                                                                                                                  [(lam am
                                                                                                                                                      [(lam an
                                                                                                                                                          [(lam ao
                                                                                                                                                              [(lam ap
                                                                                                                                                                  [(lam aq
                                                                                                                                                                      [(lam ar
                                                                                                                                                                          [(lam as
                                                                                                                                                                              [(lam at
                                                                                                                                                                                  [(lam au
                                                                                                                                                                                      (case [b
                                                                                                                                                                                          au] (error)
                                                                                                                                                                                        (error)
                                                                                                                                                                                        (case [(builtin equalsData)
                                                                                                                                                                                            [c
                                                                                                                                                                                              [e
                                                                                                                                                                                                au]]
                                                                                                                                                                                            x] (error)
                                                                                                                                                                                          (con unit ()))))
                                                                                                                                                                                    [(builtin unConstrData)
                                                                                                                                                                                      [c
                                                                                                                                                                                        [u
                                                                                                                                                                                          ah]]]])
                                                                                                                                                                                (case [(builtin equalsInteger)
                                                                                                                                                                                    ao
                                                                                                                                                                                    [r
                                                                                                                                                                                      [(builtin multiplyInteger)
                                                                                                                                                                                        [r
                                                                                                                                                                                          [ar
                                                                                                                                                                                            ad]
                                                                                                                                                                                          [r
                                                                                                                                                                                            [ar
                                                                                                                                                                                              [(builtin unIData)
                                                                                                                                                                                                [c
                                                                                                                                                                                                  [a
                                                                                                                                                                                                    (con integer 3)
                                                                                                                                                                                                    y]]]]
                                                                                                                                                                                            as]]
                                                                                                                                                                                        [(builtin unIData)
                                                                                                                                                                                          [c
                                                                                                                                                                                            [u
                                                                                                                                                                                              y]]]]
                                                                                                                                                                                      as]] (error)
                                                                                                                                                                                  (con unit ()))])
                                                                                                                                                                            [(builtin unIData)
                                                                                                                                                                              [c
                                                                                                                                                                                [a
                                                                                                                                                                                  (con integer 6)
                                                                                                                                                                                  y]]]])
                                                                                                                                                                        [(builtin subtractInteger)
                                                                                                                                                                          [(builtin unIData)
                                                                                                                                                                            [c
                                                                                                                                                                              z]]]])
                                                                                                                                                                    (case [(builtin lessThanInteger)
                                                                                                                                                                        ao
                                                                                                                                                                        an] (error)
                                                                                                                                                                      (con unit ()))])
                                                                                                                                                                (case [(builtin lessThanInteger)
                                                                                                                                                                    (con integer 0)
                                                                                                                                                                    ao] (error)
                                                                                                                                                                  (con unit ()))])
                                                                                                                                                            (case (constr 0 [c
                                                                                                                                                                  [f
                                                                                                                                                                    ah]]
                                                                                                                                                                al
                                                                                                                                                                am) q)])
                                                                                                                                                        (case (constr 0 [c
                                                                                                                                                              [f
                                                                                                                                                                ae]]
                                                                                                                                                            al
                                                                                                                                                            am) q)])
                                                                                                                                                    [(builtin unBData)
                                                                                                                                                      ak]])
                                                                                                                                                [(builtin unBData)
                                                                                                                                                  aj]])
                                                                                                                                            [c
                                                                                                                                              [f
                                                                                                                                                ai]]])
                                                                                                                                        [c
                                                                                                                                          ai]])
                                                                                                                                    [e
                                                                                                                                      [(builtin unConstrData)
                                                                                                                                        [c
                                                                                                                                          [f
                                                                                                                                            y]]]]])
                                                                                                                                (case [(builtin unListData)
                                                                                                                                    [(lam av
                                                                                                                                        (lam aw
                                                                                                                                          [n
                                                                                                                                            [(builtin unListData)
                                                                                                                                              [c
                                                                                                                                                [u
                                                                                                                                                  av]]]
                                                                                                                                            (lam ax
                                                                                                                                              [(builtin equalsData)
                                                                                                                                                [c
                                                                                                                                                  [e
                                                                                                                                                    [(builtin unConstrData)
                                                                                                                                                      [c
                                                                                                                                                        [e
                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                            ax]]]]]]
                                                                                                                                                aw])]))
                                                                                                                                      [e
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            t]]]
                                                                                                                                      af]] (lam ay
                                                                                                                                    (lam az
                                                                                                                                      [e
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          ay]]))
                                                                                                                                  (error))])
                                                                                                                            (case [(builtin equalsInteger)
                                                                                                                                [(builtin unIData)
                                                                                                                                  (case (constr 0 [(builtin unListData)
                                                                                                                                        [(lam ba
                                                                                                                                            (lam bb
                                                                                                                                              [n
                                                                                                                                                [(builtin unListData)
                                                                                                                                                  [c
                                                                                                                                                    ba]]
                                                                                                                                                (lam bc
                                                                                                                                                  [(builtin equalsData)
                                                                                                                                                    [c
                                                                                                                                                      [e
                                                                                                                                                        [(builtin unConstrData)
                                                                                                                                                          [c
                                                                                                                                                            [e
                                                                                                                                                              [(builtin unConstrData)
                                                                                                                                                                [c
                                                                                                                                                                  [f
                                                                                                                                                                    [e
                                                                                                                                                                      [(builtin unConstrData)
                                                                                                                                                                        bc]]]]]]]]]]
                                                                                                                                                    bb])]))
                                                                                                                                          [e
                                                                                                                                            [(builtin unConstrData)
                                                                                                                                              [c
                                                                                                                                                t]]]
                                                                                                                                          af]]
                                                                                                                                      (con data (I 0))
                                                                                                                                      (lam bd
                                                                                                                                        [(lam be
                                                                                                                                            (lam bf
                                                                                                                                              [(builtin iData)
                                                                                                                                                [(builtin addInteger)
                                                                                                                                                  be
                                                                                                                                                  (con integer 1)]]))
                                                                                                                                          [(builtin unIData)
                                                                                                                                            bd]])) l)]
                                                                                                                                (con integer 1)] (error)
                                                                                                                              (con unit ()))])
                                                                                                                        [c
                                                                                                                          [e
                                                                                                                            [(builtin unConstrData)
                                                                                                                              [c
                                                                                                                                ae]]]]])
                                                                                                                    [e
                                                                                                                      [(builtin unConstrData)
                                                                                                                        [c
                                                                                                                          [f
                                                                                                                            [e
                                                                                                                              [(builtin unConstrData)
                                                                                                                                [(lam bg
                                                                                                                                    (case [b
                                                                                                                                        bg] [c
                                                                                                                                        [e
                                                                                                                                          bg]]
                                                                                                                                      (error)))
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [(lam bh
                                                                                                                                        (lam bi
                                                                                                                                          [(lam bj
                                                                                                                                              (lam bk
                                                                                                                                                [h
                                                                                                                                                  bj
                                                                                                                                                  [(lam bl
                                                                                                                                                      (lam bm
                                                                                                                                                        [(builtin equalsData)
                                                                                                                                                          [c
                                                                                                                                                            [e
                                                                                                                                                              [(builtin unConstrData)
                                                                                                                                                                bm]]]
                                                                                                                                                          bl]))
                                                                                                                                                    [(builtin constrData)
                                                                                                                                                      (con integer 0)
                                                                                                                                                      bk]]]))
                                                                                                                                            [(builtin unListData)
                                                                                                                                              [c
                                                                                                                                                bh]]
                                                                                                                                            bi]))
                                                                                                                                      [e
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            t]]]
                                                                                                                                      [e
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            w]]]]]]]]]]]]])
                                                                                                                [(lam bn
                                                                                                                    (case [b
                                                                                                                        bn] (con integer 0)
                                                                                                                      [(builtin unIData)
                                                                                                                        [c
                                                                                                                          [e
                                                                                                                            bn]]]
                                                                                                                      (con integer 0)))
                                                                                                                  [(builtin unConstrData)
                                                                                                                    [c
                                                                                                                      [e
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            [e
                                                                                                                              [(builtin unConstrData)
                                                                                                                                [c
                                                                                                                                  [aa
                                                                                                                                    [e
                                                                                                                                      [(builtin unConstrData)
                                                                                                                                        [c
                                                                                                                                          t]]]]]]]]]]]]]])
                                                                                                            (case [k
                                                                                                                [e
                                                                                                                  [(builtin unConstrData)
                                                                                                                    [c
                                                                                                                      [aa
                                                                                                                        [e
                                                                                                                          [(builtin unConstrData)
                                                                                                                            [c
                                                                                                                              t]]]]]]]
                                                                                                                [(builtin unIData)
                                                                                                                  [c
                                                                                                                    [a
                                                                                                                      (con integer 5)
                                                                                                                      y]]]] (error)
                                                                                                              (con unit ()))])
                                                                                                        (case [i
                                                                                                            [e
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  t]]]
                                                                                                            [j
                                                                                                              y]] (error)
                                                                                                          (con unit ()))]
                                                                                                      [(lam bo
                                                                                                          (case [k
                                                                                                              [e
                                                                                                                [(builtin unConstrData)
                                                                                                                  [c
                                                                                                                    [aa
                                                                                                                      [e
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            t]]]]]]]
                                                                                                              [(builtin unIData)
                                                                                                                [c
                                                                                                                  z]]] (error)
                                                                                                            (con unit ())))
                                                                                                        (case [i
                                                                                                            [e
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  t]]]
                                                                                                            [j
                                                                                                              y]] (error)
                                                                                                          (con unit ()))]))
                                                                                                  [a
                                                                                                    (con integer 7)]])
                                                                                              [a
                                                                                                (con integer 4)
                                                                                                y]])
                                                                                          [e
                                                                                            [(builtin unConstrData)
                                                                                              x]]])
                                                                                      [(lam bp
                                                                                          (case [b
                                                                                              bp] [c
                                                                                              [e
                                                                                                bp]]
                                                                                            (error)))
                                                                                        [(builtin unConstrData)
                                                                                          [c
                                                                                            [f
                                                                                              w]]]]])
                                                                                  [e
                                                                                    v]]
                                                                                (error)
                                                                                (error)
                                                                                (error)
                                                                                (error)))
                                                                            [(builtin unConstrData)
                                                                              [c
                                                                                [u
                                                                                  t]]]])
                                                                        [a
                                                                          (con integer 2)]])
                                                                    [e
                                                                      [(builtin unConstrData)
                                                                        s]]]))
                                                              (lam bq
                                                                (lam br
                                                                  [(builtin addInteger)
                                                                    (con integer 1)
                                                                    [(builtin divideInteger)
                                                                      [(builtin subtractInteger)
                                                                        bq
                                                                        (con integer 1)]
                                                                      br]]))])
                                                          (lam bs
                                                            (lam bt
                                                              [(lam bu
                                                                  (lam bv
                                                                    [(lam bw
                                                                        (case [b
                                                                            bw] [(builtin unIData)
                                                                            [(lam bx
                                                                                (lam by
                                                                                  (case [b
                                                                                      bx] [c
                                                                                      [e
                                                                                        bx]]
                                                                                    by)))
                                                                              [(builtin unConstrData)
                                                                                (case (constr 0 [c
                                                                                      [e
                                                                                        bw]]
                                                                                    [(builtin bData)
                                                                                      bv]
                                                                                    (lam bz
                                                                                      [(lam ca
                                                                                          (lam cb
                                                                                            [p
                                                                                              ca
                                                                                              [(builtin unBData)
                                                                                                cb]]))
                                                                                        [(builtin unBData)
                                                                                          bz]])) o)]
                                                                              (con data (I 0))]]
                                                                          (con integer 0)))
                                                                      [(builtin unConstrData)
                                                                        (case (constr 0 bs
                                                                            bu
                                                                            (lam cc
                                                                              [(lam cd
                                                                                  (lam ce
                                                                                    [p
                                                                                      cd
                                                                                      [(builtin unBData)
                                                                                        ce]]))
                                                                                [(builtin unBData)
                                                                                  cc]])) o)]]))
                                                                [(builtin bData)
                                                                  bt]]))])
                                                      (lam cf
                                                        (lam cg
                                                          (case [(builtin lessThanByteString)
                                                              cf
                                                              cg] (case [(builtin equalsByteString)
                                                                cf
                                                                cg] (con data (Constr 2 []))
                                                              (con data (Constr 1 [])))
                                                            (con data (Constr 0 [])))))])
                                                  (lam ch
                                                    (lam ci
                                                      (lam cj
                                                        [g (lam ck
                                                            (lam cl
                                                              (case cl (lam cm
                                                                  (lam cn
                                                                    (case cm (lam co
                                                                        (lam cp
                                                                          (case [b
                                                                              [(builtin unConstrData)
                                                                                [cj
                                                                                  ci
                                                                                  co]]] (con data (Constr 1 []))
                                                                            [(builtin constrData)
                                                                              (con integer 0)
                                                                              [d
                                                                                cp
                                                                                (con (list data) [])]]
                                                                            [ck
                                                                              cn]))))))
                                                                (con data (Constr 1 [])))))
                                                          [(builtin unMapData)
                                                            ch]])))]) (lam cq
                                                (lam cr
                                                  (case (constr 0 cq
                                                      (con data (List []))
                                                      (lam cs
                                                        (lam ct
                                                          [(builtin listData)
                                                            [(lam cu
                                                                (case [cr cs] cu
                                                                  [d cs cu]))
                                                              [(builtin unListData)
                                                                ct]]]))) m)))])
                                          [g (lam m
                                              (lam cv
                                                (lam cw
                                                  (lam cx
                                                    (case cv (lam cy
                                                        (lam cz
                                                          [cx cy
                                                            (case (constr 0 cz
                                                                cw cx) m)]))
                                                      cw)))))]]) [g (lam l
                                          (lam da
                                            (lam db
                                              (lam dc
                                                (case da (lam dd
                                                    (lam de
                                                      (case (constr 0 de [dc db
                                                            dd] dc) l)))
                                                  db)))))]]) (lam df
                                    (lam dg
                                      [(lam dh
                                          [(lam di
                                              (case [b di] (con bool False)
                                                [(lam dj
                                                    (case (case [b
                                                          [(builtin unConstrData)
                                                            [c [f
                                                                dh]]]] (con bool False)
                                                        (con bool True)) [(builtin lessThanEqualsInteger)
                                                        dg [(builtin unIData) [c
                                                            dj]]]
                                                      [(builtin lessThanInteger)
                                                        dg [(builtin unIData) [c
                                                            dj]]])) [e di]]
                                                (con bool False)))
                                            [(builtin unConstrData) [c dh]]]) [e
                                          [(builtin unConstrData) [c df]]]]))])
                              (lam dk
                                [(lam dl
                                    (case [b dl] [(builtin unBData) [c [e dl]]]
                                      (error))) [(builtin unConstrData) [c [e
                                        [(builtin unConstrData) [c dk]]]]]])])
                          (lam dm
                            (lam dn
                              (case (constr 0 [(builtin unListData) [c [a
                                        (con integer 8) dm]]] [(builtin bData)
                                    dn] (lam do
                                    [(lam dp
                                        (lam dq
                                          [(builtin equalsByteString) dp
                                            [(builtin unBData) dq]]))
                                      [(builtin unBData) do]])) (lam dr
                                  (lam ds
                                    (lam dt
                                      (case (case [b [(builtin unConstrData) [h
                                                dr (lam du
                                                  [(builtin equalsData) du
                                                    ds])]]] (con bool False)
                                          (con bool True)) (con bool True)
                                        (con bool False))))))))]) [g (lam h
                          (lam dv
                            (lam dw
                              (case dv (lam dx
                                  (lam dy
                                    (case [dw dx] [h dy dw]
                                      [(builtin constrData) (con integer 0) [d
                                          dx (con (list data) [])]])))
                                (con data (Constr 1 []))))))]]) (lam dz
                    [(lam ea [dz (lam eb [ea ea eb])]) (lam ea
                        [dz (lam eb [ea ea eb])])])]))))))))