(program 1.1.0 (case (constr 0 (force (force (builtin chooseList)))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin ifThenElse)) (force (builtin mkCons))
      (force (force (builtin sndPair))) (force (builtin tailList))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                (lam g
                  [(lam h
                      [(lam i
                          [(lam j
                              [(lam k
                                  [(lam l
                                      [(lam m
                                          [(lam n
                                              [(lam o
                                                  [(lam p
                                                      [(lam q
                                                          [(lam r
                                                              [(lam s
                                                                  (lam t
                                                                    [(lam u
                                                                        [(lam v
                                                                            [(lam w
                                                                                (force (case (constr 0 [(builtin equalsInteger)
                                                                                      [b
                                                                                        w]
                                                                                      (con integer 1)]
                                                                                    (delay [(lam x
                                                                                        [(lam y
                                                                                            (force (case (constr 0 [(builtin equalsInteger)
                                                                                                  [b
                                                                                                    [(builtin unConstrData)
                                                                                                      [c
                                                                                                        v]]]
                                                                                                  (con integer 0)]
                                                                                                (delay [(lam z
                                                                                                    [(lam aa
                                                                                                        [(lam ab
                                                                                                            [(lam ac
                                                                                                                [(lam ad
                                                                                                                    [(lam ae
                                                                                                                        [(lam af
                                                                                                                            [(lam ag
                                                                                                                                [(lam ah
                                                                                                                                    [(lam ai
                                                                                                                                        [(lam aj
                                                                                                                                            [(lam ak
                                                                                                                                                [(lam al
                                                                                                                                                    [(lam am
                                                                                                                                                        [(lam an
                                                                                                                                                            [(lam ao
                                                                                                                                                                [(lam ap
                                                                                                                                                                    [(lam aq
                                                                                                                                                                        [(lam ar
                                                                                                                                                                            (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                                                                  [b
                                                                                                                                                                                    ar]
                                                                                                                                                                                  (con integer 2)]
                                                                                                                                                                                (delay (force (case (constr 0 [(builtin equalsData)
                                                                                                                                                                                      [c
                                                                                                                                                                                        [f
                                                                                                                                                                                          ar]]
                                                                                                                                                                                      y]
                                                                                                                                                                                    (delay (con unit ()))
                                                                                                                                                                                    (delay (error))) d)))
                                                                                                                                                                                (delay (error))) d)))
                                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                                            [c
                                                                                                                                                                              [g
                                                                                                                                                                                am]]]])
                                                                                                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                                                            an
                                                                                                                                                                            [(lam as
                                                                                                                                                                                (lam at
                                                                                                                                                                                  [(lam au
                                                                                                                                                                                      [(lam av
                                                                                                                                                                                          [(lam aw
                                                                                                                                                                                              [(lam ax
                                                                                                                                                                                                  [(lam ay
                                                                                                                                                                                                      [s
                                                                                                                                                                                                        [(builtin multiplyInteger)
                                                                                                                                                                                                          [s
                                                                                                                                                                                                            [ay
                                                                                                                                                                                                              at]
                                                                                                                                                                                                            [s
                                                                                                                                                                                                              [ay
                                                                                                                                                                                                                [(builtin unIData)
                                                                                                                                                                                                                  [c
                                                                                                                                                                                                                    av]]]
                                                                                                                                                                                                              ax]]
                                                                                                                                                                                                          [(builtin unIData)
                                                                                                                                                                                                            [c
                                                                                                                                                                                                              au]]]
                                                                                                                                                                                                        ax])
                                                                                                                                                                                                    [(builtin subtractInteger)
                                                                                                                                                                                                      [(builtin unIData)
                                                                                                                                                                                                        [c
                                                                                                                                                                                                          aw]]]])
                                                                                                                                                                                                [(builtin unIData)
                                                                                                                                                                                                  [c
                                                                                                                                                                                                    [g
                                                                                                                                                                                                      [g
                                                                                                                                                                                                        aw]]]]])
                                                                                                                                                                                            [g
                                                                                                                                                                                              av]])
                                                                                                                                                                                        [g
                                                                                                                                                                                          au]])
                                                                                                                                                                                    [g
                                                                                                                                                                                      [g
                                                                                                                                                                                        as]]]))
                                                                                                                                                                              [f
                                                                                                                                                                                [(builtin unConstrData)
                                                                                                                                                                                  y]]
                                                                                                                                                                              ab]]
                                                                                                                                                                          (delay (con unit ()))
                                                                                                                                                                          (delay (error))) d))])
                                                                                                                                                                  (force (case (constr 0 [(builtin lessThanInteger)
                                                                                                                                                                        an
                                                                                                                                                                        al]
                                                                                                                                                                      (delay (con unit ()))
                                                                                                                                                                      (delay (error))) d))])
                                                                                                                                                              (force (case (constr 0 [(builtin lessThanInteger)
                                                                                                                                                                    (con integer 0)
                                                                                                                                                                    an]
                                                                                                                                                                  (delay (con unit ()))
                                                                                                                                                                  (delay (error))) d))])
                                                                                                                                                          (case (constr 0 [c
                                                                                                                                                                am]
                                                                                                                                                              aj
                                                                                                                                                              ak) r)])
                                                                                                                                                      [g
                                                                                                                                                        [f
                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                            af]]]])
                                                                                                                                                  (case (constr 0 [c
                                                                                                                                                        [g
                                                                                                                                                          ac]]
                                                                                                                                                      aj
                                                                                                                                                      ak) r)])
                                                                                                                                              [(builtin unBData)
                                                                                                                                                ai]])
                                                                                                                                          [(builtin unBData)
                                                                                                                                            ah]])
                                                                                                                                      [c
                                                                                                                                        [g
                                                                                                                                          ag]]])
                                                                                                                                  [c
                                                                                                                                    ag]])
                                                                                                                              [f
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  [c
                                                                                                                                    [g
                                                                                                                                      [f
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          y]]]]]]])
                                                                                                                          [(lam az
                                                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                    [b
                                                                                                                                      az]
                                                                                                                                    (con integer 0)]
                                                                                                                                  (delay [c
                                                                                                                                    [f
                                                                                                                                      az]])
                                                                                                                                  (delay (error))) d)))
                                                                                                                            [(builtin unConstrData)
                                                                                                                              [(lam ba
                                                                                                                                  (force (case (constr 0 ba
                                                                                                                                      (delay (con data (Constr 1 [])))
                                                                                                                                      (delay [(builtin constrData)
                                                                                                                                        (con integer 0)
                                                                                                                                        [e
                                                                                                                                          [c
                                                                                                                                            ba]
                                                                                                                                          (con (list data) [])]])) a)))
                                                                                                                                [(builtin unListData)
                                                                                                                                  [(lam bb
                                                                                                                                      (lam bc
                                                                                                                                        [o
                                                                                                                                          [(builtin unListData)
                                                                                                                                            [c
                                                                                                                                              [g
                                                                                                                                                [g
                                                                                                                                                  bb]]]]
                                                                                                                                          (lam bd
                                                                                                                                            [(builtin equalsData)
                                                                                                                                              [c
                                                                                                                                                [f
                                                                                                                                                  [(builtin unConstrData)
                                                                                                                                                    [c
                                                                                                                                                      [f
                                                                                                                                                        [(builtin unConstrData)
                                                                                                                                                          bd]]]]]]
                                                                                                                                              bc])]))
                                                                                                                                    [f
                                                                                                                                      [(builtin unConstrData)
                                                                                                                                        [c
                                                                                                                                          u]]]
                                                                                                                                    ad]]]]]])
                                                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                            [(builtin unIData)
                                                                                                                              (case (constr 0 [(builtin unListData)
                                                                                                                                    [(lam be
                                                                                                                                        (lam bf
                                                                                                                                          [o
                                                                                                                                            [(builtin unListData)
                                                                                                                                              [c
                                                                                                                                                be]]
                                                                                                                                            (lam bg
                                                                                                                                              [(builtin equalsData)
                                                                                                                                                [c
                                                                                                                                                  [f
                                                                                                                                                    [(builtin unConstrData)
                                                                                                                                                      [c
                                                                                                                                                        [f
                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                            [c
                                                                                                                                                              [g
                                                                                                                                                                [f
                                                                                                                                                                  [(builtin unConstrData)
                                                                                                                                                                    bg]]]]]]]]]]
                                                                                                                                                bf])]))
                                                                                                                                      [f
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            u]]]
                                                                                                                                      ad]]
                                                                                                                                  (con data (I 0))
                                                                                                                                  (lam bh
                                                                                                                                    [(lam bi
                                                                                                                                        (lam bj
                                                                                                                                          [(builtin iData)
                                                                                                                                            [(builtin addInteger)
                                                                                                                                              bi
                                                                                                                                              (con integer 1)]]))
                                                                                                                                      [(builtin unIData)
                                                                                                                                        bh]])) m)]
                                                                                                                            (con integer 1)]
                                                                                                                          (delay (con unit ()))
                                                                                                                          (delay (error))) d))])
                                                                                                                  [c
                                                                                                                    [f
                                                                                                                      [(builtin unConstrData)
                                                                                                                        [c
                                                                                                                          ac]]]]])
                                                                                                              [f
                                                                                                                [(builtin unConstrData)
                                                                                                                  [c
                                                                                                                    [g
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [(lam bk
                                                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                    [b
                                                                                                                                      bk]
                                                                                                                                    (con integer 0)]
                                                                                                                                  (delay [c
                                                                                                                                    [f
                                                                                                                                      bk]])
                                                                                                                                  (delay (error))) d)))
                                                                                                                            [(builtin unConstrData)
                                                                                                                              [(lam bl
                                                                                                                                  (lam bm
                                                                                                                                    [(lam bn
                                                                                                                                        (lam bo
                                                                                                                                          [i
                                                                                                                                            bn
                                                                                                                                            [(lam bp
                                                                                                                                                (lam bq
                                                                                                                                                  [(builtin equalsData)
                                                                                                                                                    [c
                                                                                                                                                      [f
                                                                                                                                                        [(builtin unConstrData)
                                                                                                                                                          bq]]]
                                                                                                                                                    bp]))
                                                                                                                                              [(builtin constrData)
                                                                                                                                                (con integer 0)
                                                                                                                                                bo]]]))
                                                                                                                                      [(builtin unListData)
                                                                                                                                        [c
                                                                                                                                          bl]]
                                                                                                                                      bm]))
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      u]]]
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      x]]]]]]]]]]]]])
                                                                                                          [(lam br
                                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                    [b
                                                                                                                      br]
                                                                                                                    (con integer 1)]
                                                                                                                  (delay [(builtin unIData)
                                                                                                                    [c
                                                                                                                      [f
                                                                                                                        br]]])
                                                                                                                  (delay (con integer 0))) d)))
                                                                                                            [(builtin unConstrData)
                                                                                                              [c
                                                                                                                [f
                                                                                                                  [(builtin unConstrData)
                                                                                                                    [c
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            [g
                                                                                                                              [g
                                                                                                                                [g
                                                                                                                                  [g
                                                                                                                                    [g
                                                                                                                                      [g
                                                                                                                                        [g
                                                                                                                                          [f
                                                                                                                                            [(builtin unConstrData)
                                                                                                                                              [c
                                                                                                                                                u]]]]]]]]]]]]]]]]]]]])
                                                                                                      (force (case (constr 0 [l
                                                                                                            [f
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [g
                                                                                                                            [g
                                                                                                                              [g
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      u]]]]]]]]]]]]]
                                                                                                            [(builtin unIData)
                                                                                                              [c
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [f
                                                                                                                            [(builtin unConstrData)
                                                                                                                              y]]]]]]]]]]
                                                                                                          (delay (con unit ()))
                                                                                                          (delay (error))) d))])
                                                                                                  (force (case (constr 0 [j
                                                                                                        [f
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              u]]]
                                                                                                        [k
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              y]]]]
                                                                                                      (delay (con unit ()))
                                                                                                      (delay (error))) d))])
                                                                                                (delay [(lam bs
                                                                                                    (force (case (constr 0 [l
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              [c
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [g
                                                                                                                            [g
                                                                                                                              [f
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  [c
                                                                                                                                    u]]]]]]]]]]]]]
                                                                                                          [(builtin unIData)
                                                                                                            [c
                                                                                                              [g
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          y]]]]]]]]]
                                                                                                        (delay (con unit ()))
                                                                                                        (delay (error))) d)))
                                                                                                  (force (case (constr 0 [j
                                                                                                        [f
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              u]]]
                                                                                                        [k
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              y]]]]
                                                                                                      (delay (con unit ()))
                                                                                                      (delay (error))) d))])) d)))
                                                                                          [(lam bt
                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                    [b
                                                                                                      bt]
                                                                                                    (con integer 0)]
                                                                                                  (delay [c
                                                                                                    [f
                                                                                                      bt]])
                                                                                                  (delay (error))) d)))
                                                                                            [(builtin unConstrData)
                                                                                              [c
                                                                                                [g
                                                                                                  x]]]]])
                                                                                      [f
                                                                                        w]])
                                                                                    (delay (error))) d)))
                                                                              [(builtin unConstrData)
                                                                                [c
                                                                                  [g
                                                                                    v]]]])
                                                                          [g
                                                                            u]])
                                                                      [f
                                                                        [(builtin unConstrData)
                                                                          t]]]))
                                                                (lam bu
                                                                  (lam bv
                                                                    [(builtin addInteger)
                                                                      (con integer 1)
                                                                      [(builtin divideInteger)
                                                                        [(builtin subtractInteger)
                                                                          bu
                                                                          (con integer 1)]
                                                                        bv]]))])
                                                            (lam bw
                                                              (lam bx
                                                                [(lam by
                                                                    (lam bz
                                                                      [(lam ca
                                                                          (force (case (constr 0 [(builtin equalsInteger)
                                                                                [b
                                                                                  ca]
                                                                                (con integer 0)]
                                                                              (delay [(builtin unIData)
                                                                                [(lam cb
                                                                                    (lam cc
                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                            [b
                                                                                              cb]
                                                                                            (con integer 0)]
                                                                                          (delay [c
                                                                                            [f
                                                                                              cb]])
                                                                                          (delay cc)) d))))
                                                                                  [(builtin unConstrData)
                                                                                    (case (constr 0 [c
                                                                                          [f
                                                                                            ca]]
                                                                                        [(builtin bData)
                                                                                          bz]
                                                                                        (lam cd
                                                                                          [(lam ce
                                                                                              (lam cf
                                                                                                [q
                                                                                                  ce
                                                                                                  [(builtin unBData)
                                                                                                    cf]]))
                                                                                            [(builtin unBData)
                                                                                              cd]])) p)]
                                                                                  (con data (I 0))]])
                                                                              (delay (con integer 0))) d)))
                                                                        [(builtin unConstrData)
                                                                          (case (constr 0 bw
                                                                              by
                                                                              (lam cg
                                                                                [(lam ch
                                                                                    (lam ci
                                                                                      [q
                                                                                        ch
                                                                                        [(builtin unBData)
                                                                                          ci]]))
                                                                                  [(builtin unBData)
                                                                                    cg]])) p)]]))
                                                                  [(builtin bData)
                                                                    bx]]))])
                                                        (lam cj
                                                          (lam ck
                                                            (force (case (constr 0 [(builtin lessThanByteString)
                                                                  cj ck]
                                                                (delay (con data (Constr 0 [])))
                                                                (delay (case (constr 0 [(builtin equalsByteString)
                                                                      cj ck]
                                                                    (con data (Constr 1 []))
                                                                    (con data (Constr 2 []))) d))) d))))])
                                                    (lam cl
                                                      (lam cm
                                                        (lam cn
                                                          [h (lam co
                                                              (lam cp
                                                                (force (case (constr 0 cp
                                                                    (delay (con data (Constr 1 [])))
                                                                    (delay [(lam cq
                                                                        [(lam cr
                                                                            (force (case (constr 0 [cr
                                                                                  (con integer 0)]
                                                                                (delay (con data (Constr 1 [])))
                                                                                (delay (force (case (constr 0 [cr
                                                                                      (con integer 1)]
                                                                                    (delay [(builtin constrData)
                                                                                      (con integer 0)
                                                                                      [e
                                                                                        [f
                                                                                          cq]
                                                                                        (con (list data) [])]])
                                                                                    (delay [co
                                                                                      [g
                                                                                        cp]])) d)))) d)))
                                                                          [(builtin equalsInteger)
                                                                            [b
                                                                              [(builtin unConstrData)
                                                                                [cn
                                                                                  cm
                                                                                  [b
                                                                                    cq]]]]]])
                                                                      [c
                                                                        cp]])) a))))
                                                            [(builtin unMapData)
                                                              cl]])))]) (lam cs
                                                  (lam ct
                                                    (case (constr 0 cs
                                                        (con data (List []))
                                                        (lam cu
                                                          (lam cv
                                                            [(builtin listData)
                                                              [(lam cw
                                                                  (force (case (constr 0 [ct
                                                                        cu]
                                                                      (delay [e
                                                                        cu cw])
                                                                      (delay cw)) d)))
                                                                [(builtin unListData)
                                                                  cv]]]))) n)))])
                                            [h (lam n
                                                (lam cx
                                                  (lam cy
                                                    (lam cz
                                                      (force (case (constr 0 cx
                                                          (delay cy) (delay [cz
                                                            [c cx]
                                                            (case (constr 0 [g
                                                                  cx] cy
                                                                cz) n)])) a))))))]])
                                        [h (lam m
                                            (lam da
                                              (lam db
                                                (lam dc
                                                  (force (case (constr 0 da
                                                      (delay db)
                                                      (delay (case (constr 0 [g
                                                            da] [dc db [c da]]
                                                          dc) m))) a))))))]])
                                    (lam dd
                                      (lam de
                                        [(lam df
                                            [(lam dg
                                                (force (case (constr 0 [(builtin equalsInteger)
                                                      [b dg] (con integer 1)]
                                                    (delay [(lam dh
                                                        (force (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                                  [b
                                                                    [(builtin unConstrData)
                                                                      [c [g
                                                                          df]]]]
                                                                  (con integer 0)]
                                                                (con bool False)
                                                                (con bool True)) d)
                                                            (delay [(builtin lessThanInteger)
                                                              de
                                                              [(builtin unIData)
                                                                [c dh]]])
                                                            (delay [(builtin lessThanEqualsInteger)
                                                              de
                                                              [(builtin unIData)
                                                                [c dh]]])) d)))
                                                      [f dg]])
                                                    (delay (con bool False))) d)))
                                              [(builtin unConstrData) [c df]]])
                                          [f [(builtin unConstrData) [c
                                                dd]]]]))]) (lam di
                                  [(lam dj
                                      (force (case (constr 0 [(builtin equalsInteger)
                                            [b dj] (con integer 0)]
                                          (delay [(builtin unBData) [c [f dj]]])
                                          (delay (error))) d)))
                                    [(builtin unConstrData) [c [f
                                          [(builtin unConstrData) [c di]]]]]])])
                            (lam dk
                              (lam dl
                                (case (constr 0 [(builtin unListData) [c [g [g
                                            [g [g [g [g [g [g dk]]]]]]]]]]
                                    [(builtin bData) dl] (lam dm
                                      [(lam dn
                                          (lam do
                                            [(builtin equalsByteString) dn
                                              [(builtin unBData) do]]))
                                        [(builtin unBData) dm]])) (lam dp
                                    (lam dq
                                      (lam dr
                                        (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                  [b [(builtin unConstrData) [i
                                                        dp (lam ds
                                                          [(builtin equalsData)
                                                            ds dq])]]]
                                                  (con integer 0)]
                                                (con bool False)
                                                (con bool True)) d)
                                            (con bool False)
                                            (con bool True)) d)))))))]) [h
                          (lam i
                            (lam dt
                              (lam du
                                (force (case (constr 0 dt
                                    (delay (con data (Constr 1 [])))
                                    (delay (force (case (constr 0 [du [c dt]]
                                        (delay [(builtin constrData)
                                          (con integer 0) [e [c dt]
                                            (con (list data) [])]]) (delay [i [g
                                            dt] du])) d)))) a)))))]]) (lam dv
                      [(lam dw [dv (lam dx [dw dw dx])]) (lam dw
                          [dv (lam dx [dw dw dx])])])])))))))))