(program 1.1.0 (case (constr 0 (force (force (builtin chooseList)))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin ifThenElse)) (force (builtin mkCons))
      (force (force (builtin sndPair))) (force (builtin tailList))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                (lam g
                  [(lam h
                      [(lam i
                          [(lam j
                              [(lam k
                                  [(lam l
                                      [(lam m
                                          [(lam n
                                              [(lam o
                                                  [(lam p
                                                      [(lam q
                                                          [(lam r
                                                              [(lam s
                                                                  (lam t
                                                                    [(lam u
                                                                        [(lam v
                                                                            [(lam w
                                                                                (force (case (constr 0 [(builtin equalsInteger)
                                                                                      [b
                                                                                        w]
                                                                                      (con integer 1)]
                                                                                    (delay [(lam x
                                                                                        [(lam y
                                                                                            (force (case (constr 0 [(builtin equalsInteger)
                                                                                                  [b
                                                                                                    [(builtin unConstrData)
                                                                                                      [c
                                                                                                        v]]]
                                                                                                  (con integer 0)]
                                                                                                (delay [(lam z
                                                                                                    [(lam aa
                                                                                                        [(lam ab
                                                                                                            [(lam ac
                                                                                                                [(lam ad
                                                                                                                    [(lam ae
                                                                                                                        [(lam af
                                                                                                                            [(lam ag
                                                                                                                                [(lam ah
                                                                                                                                    [(lam ai
                                                                                                                                        [(lam aj
                                                                                                                                            [(lam ak
                                                                                                                                                [(lam al
                                                                                                                                                    [(lam am
                                                                                                                                                        [(lam an
                                                                                                                                                            [(lam ao
                                                                                                                                                                [(lam ap
                                                                                                                                                                    [(lam aq
                                                                                                                                                                        [(lam ar
                                                                                                                                                                            (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                                                                  [b
                                                                                                                                                                                    ar]
                                                                                                                                                                                  (con integer 2)]
                                                                                                                                                                                (delay (force (case (constr 0 [(builtin equalsData)
                                                                                                                                                                                      [c
                                                                                                                                                                                        [f
                                                                                                                                                                                          ar]]
                                                                                                                                                                                      y]
                                                                                                                                                                                    (delay (con unit ()))
                                                                                                                                                                                    (delay (error))) d)))
                                                                                                                                                                                (delay (error))) d)))
                                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                                            [c
                                                                                                                                                                              [g
                                                                                                                                                                                am]]]])
                                                                                                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                                                            an
                                                                                                                                                                            [(lam as
                                                                                                                                                                                (lam at
                                                                                                                                                                                  [(lam au
                                                                                                                                                                                      [(lam av
                                                                                                                                                                                          [(lam aw
                                                                                                                                                                                              [(lam ax
                                                                                                                                                                                                  [(lam ay
                                                                                                                                                                                                      [s
                                                                                                                                                                                                        [(builtin multiplyInteger)
                                                                                                                                                                                                          [s
                                                                                                                                                                                                            [ay
                                                                                                                                                                                                              at]
                                                                                                                                                                                                            [s
                                                                                                                                                                                                              [ay
                                                                                                                                                                                                                [(builtin unIData)
                                                                                                                                                                                                                  [c
                                                                                                                                                                                                                    av]]]
                                                                                                                                                                                                              ax]]
                                                                                                                                                                                                          [(builtin unIData)
                                                                                                                                                                                                            [c
                                                                                                                                                                                                              au]]]
                                                                                                                                                                                                        ax])
                                                                                                                                                                                                    [(builtin subtractInteger)
                                                                                                                                                                                                      [(builtin unIData)
                                                                                                                                                                                                        [c
                                                                                                                                                                                                          aw]]]])
                                                                                                                                                                                                [(builtin unIData)
                                                                                                                                                                                                  [c
                                                                                                                                                                                                    [g
                                                                                                                                                                                                      [g
                                                                                                                                                                                                        aw]]]]])
                                                                                                                                                                                            [g
                                                                                                                                                                                              av]])
                                                                                                                                                                                        [g
                                                                                                                                                                                          au]])
                                                                                                                                                                                    [g
                                                                                                                                                                                      [g
                                                                                                                                                                                        as]]]))
                                                                                                                                                                              [f
                                                                                                                                                                                [(builtin unConstrData)
                                                                                                                                                                                  y]]
                                                                                                                                                                              ab]]
                                                                                                                                                                          (delay (con unit ()))
                                                                                                                                                                          (delay (error))) d))])
                                                                                                                                                                  (force (case (constr 0 [(builtin lessThanInteger)
                                                                                                                                                                        an
                                                                                                                                                                        al]
                                                                                                                                                                      (delay (con unit ()))
                                                                                                                                                                      (delay (error))) d))])
                                                                                                                                                              (force (case (constr 0 [(builtin lessThanInteger)
                                                                                                                                                                    (con integer 0)
                                                                                                                                                                    an]
                                                                                                                                                                  (delay (con unit ()))
                                                                                                                                                                  (delay (error))) d))])
                                                                                                                                                          (case (constr 0 [c
                                                                                                                                                                am]
                                                                                                                                                              aj
                                                                                                                                                              ak) r)])
                                                                                                                                                      [g
                                                                                                                                                        af]])
                                                                                                                                                  (case (constr 0 [c
                                                                                                                                                        [g
                                                                                                                                                          ac]]
                                                                                                                                                      aj
                                                                                                                                                      ak) r)])
                                                                                                                                              [(builtin unBData)
                                                                                                                                                ai]])
                                                                                                                                          [(builtin unBData)
                                                                                                                                            ah]])
                                                                                                                                      [c
                                                                                                                                        [g
                                                                                                                                          ag]]])
                                                                                                                                  [c
                                                                                                                                    ag]])
                                                                                                                              [f
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  [c
                                                                                                                                    [g
                                                                                                                                      [f
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          y]]]]]]])
                                                                                                                          [(lam az
                                                                                                                              (force (case (constr 0 az
                                                                                                                                  (delay (error))
                                                                                                                                  (delay [f
                                                                                                                                    [(builtin unConstrData)
                                                                                                                                      [c
                                                                                                                                        az]]])) a)))
                                                                                                                            [(builtin unListData)
                                                                                                                              [(lam ba
                                                                                                                                  (lam bb
                                                                                                                                    [o
                                                                                                                                      [(builtin unListData)
                                                                                                                                        [c
                                                                                                                                          [g
                                                                                                                                            [g
                                                                                                                                              ba]]]]
                                                                                                                                      (lam bc
                                                                                                                                        [(builtin equalsData)
                                                                                                                                          [c
                                                                                                                                            [f
                                                                                                                                              [(builtin unConstrData)
                                                                                                                                                [c
                                                                                                                                                  [f
                                                                                                                                                    [(builtin unConstrData)
                                                                                                                                                      bc]]]]]]
                                                                                                                                          bb])]))
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      u]]]
                                                                                                                                ad]]]])
                                                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                            [(builtin unIData)
                                                                                                                              (case (constr 0 [(builtin unListData)
                                                                                                                                    [(lam bd
                                                                                                                                        (lam be
                                                                                                                                          [o
                                                                                                                                            [(builtin unListData)
                                                                                                                                              [c
                                                                                                                                                bd]]
                                                                                                                                            (lam bf
                                                                                                                                              [(builtin equalsData)
                                                                                                                                                [c
                                                                                                                                                  [f
                                                                                                                                                    [(builtin unConstrData)
                                                                                                                                                      [c
                                                                                                                                                        [f
                                                                                                                                                          [(builtin unConstrData)
                                                                                                                                                            [c
                                                                                                                                                              [g
                                                                                                                                                                [f
                                                                                                                                                                  [(builtin unConstrData)
                                                                                                                                                                    bf]]]]]]]]]]
                                                                                                                                                be])]))
                                                                                                                                      [f
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            u]]]
                                                                                                                                      ad]]
                                                                                                                                  (con data (I 0))
                                                                                                                                  (lam bg
                                                                                                                                    [(lam bh
                                                                                                                                        (lam bi
                                                                                                                                          [(builtin iData)
                                                                                                                                            [(builtin addInteger)
                                                                                                                                              bh
                                                                                                                                              (con integer 1)]]))
                                                                                                                                      [(builtin unIData)
                                                                                                                                        bg]])) m)]
                                                                                                                            (con integer 1)]
                                                                                                                          (delay (con unit ()))
                                                                                                                          (delay (error))) d))])
                                                                                                                  [c
                                                                                                                    [f
                                                                                                                      [(builtin unConstrData)
                                                                                                                        [c
                                                                                                                          ac]]]]])
                                                                                                              [f
                                                                                                                [(builtin unConstrData)
                                                                                                                  [c
                                                                                                                    [g
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [(lam bj
                                                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                                    [b
                                                                                                                                      bj]
                                                                                                                                    (con integer 0)]
                                                                                                                                  (delay [c
                                                                                                                                    [f
                                                                                                                                      bj]])
                                                                                                                                  (delay (error))) d)))
                                                                                                                            [(builtin unConstrData)
                                                                                                                              [(lam bk
                                                                                                                                  (lam bl
                                                                                                                                    [(lam bm
                                                                                                                                        (lam bn
                                                                                                                                          [i
                                                                                                                                            bm
                                                                                                                                            [(lam bo
                                                                                                                                                (lam bp
                                                                                                                                                  [(builtin equalsData)
                                                                                                                                                    [c
                                                                                                                                                      [f
                                                                                                                                                        [(builtin unConstrData)
                                                                                                                                                          bp]]]
                                                                                                                                                    bo]))
                                                                                                                                              [(builtin constrData)
                                                                                                                                                (con integer 0)
                                                                                                                                                bn]]]))
                                                                                                                                      [(builtin unListData)
                                                                                                                                        [c
                                                                                                                                          bk]]
                                                                                                                                      bl]))
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      u]]]
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      x]]]]]]]]]]]]])
                                                                                                          [(lam bq
                                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                    [b
                                                                                                                      bq]
                                                                                                                    (con integer 1)]
                                                                                                                  (delay [(builtin unIData)
                                                                                                                    [c
                                                                                                                      [f
                                                                                                                        bq]]])
                                                                                                                  (delay (con integer 0))) d)))
                                                                                                            [(builtin unConstrData)
                                                                                                              [c
                                                                                                                [f
                                                                                                                  [(builtin unConstrData)
                                                                                                                    [c
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            [g
                                                                                                                              [g
                                                                                                                                [g
                                                                                                                                  [g
                                                                                                                                    [g
                                                                                                                                      [g
                                                                                                                                        [g
                                                                                                                                          [f
                                                                                                                                            [(builtin unConstrData)
                                                                                                                                              [c
                                                                                                                                                u]]]]]]]]]]]]]]]]]]]])
                                                                                                      (force (case (constr 0 [l
                                                                                                            [f
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [g
                                                                                                                            [g
                                                                                                                              [g
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      u]]]]]]]]]]]]]
                                                                                                            [(builtin unIData)
                                                                                                              [c
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [f
                                                                                                                            [(builtin unConstrData)
                                                                                                                              y]]]]]]]]]]
                                                                                                          (delay (con unit ()))
                                                                                                          (delay (error))) d))])
                                                                                                  (force (case (constr 0 [j
                                                                                                        [f
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              u]]]
                                                                                                        [k
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              y]]]]
                                                                                                      (delay (con unit ()))
                                                                                                      (delay (error))) d))])
                                                                                                (delay [(lam br
                                                                                                    (force (case (constr 0 [l
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              [c
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          [g
                                                                                                                            [g
                                                                                                                              [f
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  [c
                                                                                                                                    u]]]]]]]]]]]]]
                                                                                                          [(builtin unIData)
                                                                                                            [c
                                                                                                              [g
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [f
                                                                                                                        [(builtin unConstrData)
                                                                                                                          y]]]]]]]]]
                                                                                                        (delay (con unit ()))
                                                                                                        (delay (error))) d)))
                                                                                                  (force (case (constr 0 [j
                                                                                                        [f
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              u]]]
                                                                                                        [k
                                                                                                          [f
                                                                                                            [(builtin unConstrData)
                                                                                                              y]]]]
                                                                                                      (delay (con unit ()))
                                                                                                      (delay (error))) d))])) d)))
                                                                                          [(lam bs
                                                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                                                    [b
                                                                                                      bs]
                                                                                                    (con integer 0)]
                                                                                                  (delay [c
                                                                                                    [f
                                                                                                      bs]])
                                                                                                  (delay (error))) d)))
                                                                                            [(builtin unConstrData)
                                                                                              [c
                                                                                                [g
                                                                                                  x]]]]])
                                                                                      [f
                                                                                        w]])
                                                                                    (delay (error))) d)))
                                                                              [(builtin unConstrData)
                                                                                [c
                                                                                  [g
                                                                                    v]]]])
                                                                          [g
                                                                            u]])
                                                                      [f
                                                                        [(builtin unConstrData)
                                                                          t]]]))
                                                                (lam bt
                                                                  (lam bu
                                                                    [(builtin addInteger)
                                                                      (con integer 1)
                                                                      [(builtin divideInteger)
                                                                        [(builtin subtractInteger)
                                                                          bt
                                                                          (con integer 1)]
                                                                        bu]]))])
                                                            (lam bv
                                                              (lam bw
                                                                [(lam bx
                                                                    (lam by
                                                                      [(lam bz
                                                                          (force (case (constr 0 [(builtin equalsInteger)
                                                                                [b
                                                                                  bz]
                                                                                (con integer 0)]
                                                                              (delay [(builtin unIData)
                                                                                [(lam ca
                                                                                    (lam cb
                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                            [b
                                                                                              ca]
                                                                                            (con integer 0)]
                                                                                          (delay [c
                                                                                            [f
                                                                                              ca]])
                                                                                          (delay cb)) d))))
                                                                                  [(builtin unConstrData)
                                                                                    (case (constr 0 [c
                                                                                          [f
                                                                                            bz]]
                                                                                        [(builtin bData)
                                                                                          by]
                                                                                        (lam cc
                                                                                          [(lam cd
                                                                                              (lam ce
                                                                                                [q
                                                                                                  cd
                                                                                                  [(builtin unBData)
                                                                                                    ce]]))
                                                                                            [(builtin unBData)
                                                                                              cc]])) p)]
                                                                                  (con data (I 0))]])
                                                                              (delay (con integer 0))) d)))
                                                                        [(builtin unConstrData)
                                                                          (case (constr 0 bv
                                                                              bx
                                                                              (lam cf
                                                                                [(lam cg
                                                                                    (lam ch
                                                                                      [q
                                                                                        cg
                                                                                        [(builtin unBData)
                                                                                          ch]]))
                                                                                  [(builtin unBData)
                                                                                    cf]])) p)]]))
                                                                  [(builtin bData)
                                                                    bw]]))])
                                                        (lam ci
                                                          (lam cj
                                                            (force (case (constr 0 [(builtin lessThanByteString)
                                                                  ci cj]
                                                                (delay (con data (Constr 0 [])))
                                                                (delay (case (constr 0 [(builtin equalsByteString)
                                                                      ci cj]
                                                                    (con data (Constr 1 []))
                                                                    (con data (Constr 2 []))) d))) d))))])
                                                    (lam ck
                                                      (lam cl
                                                        (lam cm
                                                          [h (lam cn
                                                              (lam co
                                                                (force (case (constr 0 co
                                                                    (delay (con data (Constr 1 [])))
                                                                    (delay [(lam cp
                                                                        [(lam cq
                                                                            (force (case (constr 0 [cq
                                                                                  (con integer 0)]
                                                                                (delay (con data (Constr 1 [])))
                                                                                (delay (force (case (constr 0 [cq
                                                                                      (con integer 1)]
                                                                                    (delay [(builtin constrData)
                                                                                      (con integer 0)
                                                                                      [e
                                                                                        [f
                                                                                          cp]
                                                                                        (con (list data) [])]])
                                                                                    (delay [cn
                                                                                      [g
                                                                                        co]])) d)))) d)))
                                                                          [(builtin equalsInteger)
                                                                            [b
                                                                              [(builtin unConstrData)
                                                                                [cm
                                                                                  cl
                                                                                  [b
                                                                                    cp]]]]]])
                                                                      [c
                                                                        co]])) a))))
                                                            [(builtin unMapData)
                                                              ck]])))]) (lam cr
                                                  (lam cs
                                                    (case (constr 0 cr
                                                        (con data (List []))
                                                        (lam ct
                                                          (lam cu
                                                            [(builtin listData)
                                                              [(lam cv
                                                                  (force (case (constr 0 [cs
                                                                        ct]
                                                                      (delay [e
                                                                        ct cv])
                                                                      (delay cv)) d)))
                                                                [(builtin unListData)
                                                                  cu]]]))) n)))])
                                            [h (lam n
                                                (lam cw
                                                  (lam cx
                                                    (lam cy
                                                      (force (case (constr 0 cw
                                                          (delay cx) (delay [cy
                                                            [c cw]
                                                            (case (constr 0 [g
                                                                  cw] cx
                                                                cy) n)])) a))))))]])
                                        [h (lam m
                                            (lam cz
                                              (lam da
                                                (lam db
                                                  (force (case (constr 0 cz
                                                      (delay da)
                                                      (delay (case (constr 0 [g
                                                            cz] [db da [c cz]]
                                                          db) m))) a))))))]])
                                    (lam dc
                                      (lam dd
                                        [(lam de
                                            [(lam df
                                                (force (case (constr 0 [(builtin equalsInteger)
                                                      [b df] (con integer 1)]
                                                    (delay [(lam dg
                                                        (force (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                                  [b
                                                                    [(builtin unConstrData)
                                                                      [c [g
                                                                          de]]]]
                                                                  (con integer 0)]
                                                                (con bool False)
                                                                (con bool True)) d)
                                                            (delay [(builtin lessThanInteger)
                                                              dd
                                                              [(builtin unIData)
                                                                [c dg]]])
                                                            (delay [(builtin lessThanEqualsInteger)
                                                              dd
                                                              [(builtin unIData)
                                                                [c dg]]])) d)))
                                                      [f df]])
                                                    (delay (con bool False))) d)))
                                              [(builtin unConstrData) [c de]]])
                                          [f [(builtin unConstrData) [c
                                                dc]]]]))]) (lam dh
                                  [(lam di
                                      (force (case (constr 0 [(builtin equalsInteger)
                                            [b di] (con integer 0)]
                                          (delay [(builtin unBData) [c [f di]]])
                                          (delay (error))) d)))
                                    [(builtin unConstrData) [c [f
                                          [(builtin unConstrData) [c dh]]]]]])])
                            (lam dj
                              (lam dk
                                (case (constr 0 [(builtin unListData) [c [g [g
                                            [g [g [g [g [g [g dj]]]]]]]]]]
                                    [(builtin bData) dk] (lam dl
                                      [(lam dm
                                          (lam dn
                                            [(builtin equalsByteString) dm
                                              [(builtin unBData) dn]]))
                                        [(builtin unBData) dl]])) (lam do
                                    (lam dp
                                      (lam dq
                                        (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                  [b [(builtin unConstrData) [i
                                                        do (lam dr
                                                          [(builtin equalsData)
                                                            dr dp])]]]
                                                  (con integer 0)]
                                                (con bool False)
                                                (con bool True)) d)
                                            (con bool False)
                                            (con bool True)) d)))))))]) [h
                          (lam i
                            (lam ds
                              (lam dt
                                (force (case (constr 0 ds
                                    (delay (con data (Constr 1 [])))
                                    (delay (force (case (constr 0 [dt [c ds]]
                                        (delay [(builtin constrData)
                                          (con integer 0) [e [c ds]
                                            (con (list data) [])]]) (delay [i [g
                                            ds] dt])) d)))) a)))))]]) (lam du
                      [(lam dv [du (lam dw [dv dv dw])]) (lam dv
                          [du (lam dw [dv dv dw])])])])))))))))