(program 1.1.0 (case (constr 0 (force (builtin dropList))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin mkCons)) (force (force (builtin sndPair)))
      (force (builtin tailList))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                [(lam g
                    [(lam h
                        [(lam i
                            [(lam j
                                [(lam k
                                    [(lam l
                                        [(lam m
                                            (lam n
                                              [(lam o
                                                  [(lam p
                                                      [(lam q
                                                          (case [b q] (error)
                                                            [(lam r
                                                                [(lam s
                                                                    [(lam t
                                                                        [(lam u
                                                                            [(lam v
                                                                                (case [b
                                                                                    t] (case (constr 0 [e
                                                                                        [(builtin unConstrData)
                                                                                          [c
                                                                                            o]]]
                                                                                      [e
                                                                                        [(builtin unConstrData)
                                                                                          [c
                                                                                            r]]]
                                                                                      s
                                                                                      [(builtin unBData)
                                                                                        [c
                                                                                          [e
                                                                                            t]]]) (lam w
                                                                                      (lam x
                                                                                        (lam y
                                                                                          (lam z
                                                                                            [(lam aa
                                                                                                [(lam ab
                                                                                                    [(lam ac
                                                                                                        (case [(builtin equalsInteger)
                                                                                                            [(builtin unIData)
                                                                                                              [l
                                                                                                                w
                                                                                                                [m
                                                                                                                  w
                                                                                                                  x]]]
                                                                                                            (con integer 1)] (error)
                                                                                                          (con unit ())))
                                                                                                      (case [(builtin lessThanInteger)
                                                                                                          [(lam ad
                                                                                                              [(lam ae
                                                                                                                  (case [b
                                                                                                                      ae] (error)
                                                                                                                    [(lam af
                                                                                                                        (case (case [b
                                                                                                                              [(builtin unConstrData)
                                                                                                                                [c
                                                                                                                                  [f
                                                                                                                                    ad]]]] (con bool False)
                                                                                                                            (con bool True)) [(builtin subtractInteger)
                                                                                                                            [(builtin unIData)
                                                                                                                              [c
                                                                                                                                af]]
                                                                                                                            (con integer 1)]
                                                                                                                          [(builtin unIData)
                                                                                                                            [c
                                                                                                                              af]]))
                                                                                                                      [e
                                                                                                                        ae]]
                                                                                                                    (error)))
                                                                                                                [(builtin unConstrData)
                                                                                                                  [c
                                                                                                                    ad]]])
                                                                                                            [e
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  [f
                                                                                                                    [e
                                                                                                                      [(builtin unConstrData)
                                                                                                                        [c
                                                                                                                          [v
                                                                                                                            w]]]]]]]]]
                                                                                                          [(builtin unIData)
                                                                                                            [c
                                                                                                              [u
                                                                                                                y]]]] (error)
                                                                                                        (con unit ()))])
                                                                                                  (case [i
                                                                                                      w
                                                                                                      [j
                                                                                                        [e
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              [f
                                                                                                                y]]]]]] (error)
                                                                                                    (con unit ()))])
                                                                                              (case [(builtin equalsByteString)
                                                                                                  [(builtin sha2_256)
                                                                                                    z]
                                                                                                  [(builtin unBData)
                                                                                                    [c
                                                                                                      [p
                                                                                                        y]]]] (error)
                                                                                                (con unit ()))])))))
                                                                                  (case (constr 0 [e
                                                                                        [(builtin unConstrData)
                                                                                          [c
                                                                                            o]]]
                                                                                      [e
                                                                                        [(builtin unConstrData)
                                                                                          [c
                                                                                            r]]]
                                                                                      s) (lam ag
                                                                                      (lam ah
                                                                                        (lam ai
                                                                                          [(lam aj
                                                                                              [(lam ak
                                                                                                  (case [(builtin equalsInteger)
                                                                                                      [(builtin unIData)
                                                                                                        [l
                                                                                                          ag
                                                                                                          [m
                                                                                                            ag
                                                                                                            ah]]]
                                                                                                      (con integer 1)] (error)
                                                                                                    (con unit ())))
                                                                                                (case [(builtin lessThanInteger)
                                                                                                    [(builtin unIData)
                                                                                                      [c
                                                                                                        [u
                                                                                                          ai]]]
                                                                                                    [(lam al
                                                                                                        [(lam am
                                                                                                            (case [b
                                                                                                                am] (error)
                                                                                                              [(lam an
                                                                                                                  (case (case [b
                                                                                                                        [(builtin unConstrData)
                                                                                                                          [c
                                                                                                                            [f
                                                                                                                              al]]]] (con bool False)
                                                                                                                      (con bool True)) [(builtin addInteger)
                                                                                                                      [(builtin unIData)
                                                                                                                        [c
                                                                                                                          an]]
                                                                                                                      (con integer 1)]
                                                                                                                    [(builtin unIData)
                                                                                                                      [c
                                                                                                                        an]]))
                                                                                                                [e
                                                                                                                  am]]
                                                                                                              (error)))
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              al]]])
                                                                                                      [e
                                                                                                        [(builtin unConstrData)
                                                                                                          [c
                                                                                                            [e
                                                                                                              [(builtin unConstrData)
                                                                                                                [c
                                                                                                                  [v
                                                                                                                    ag]]]]]]]]] (error)
                                                                                                  (con unit ()))])
                                                                                            (case [i
                                                                                                ag
                                                                                                [j
                                                                                                  [e
                                                                                                    [(builtin unConstrData)
                                                                                                      [c
                                                                                                        ai]]]]] (error)
                                                                                              (con unit ()))]))))))
                                                                              [a
                                                                                (con integer 7)]])
                                                                          [a
                                                                            (con integer 3)]])
                                                                      [(builtin unConstrData)
                                                                        [c [f
                                                                            o]]]])
                                                                  [(lam ao
                                                                      (case [b
                                                                          ao] [e
                                                                          [(builtin unConstrData)
                                                                            [c
                                                                              [e
                                                                                ao]]]]
                                                                        (error)))
                                                                    [(builtin unConstrData)
                                                                      [c [f
                                                                          r]]]]])
                                                              [e q]] (error)
                                                            (error) (error)
                                                            (error)))
                                                        [(builtin unConstrData)
                                                          [c [p o]]]]) [a
                                                      (con integer 2)]]) [e
                                                  [(builtin unConstrData) n]]]))
                                          (lam ap
                                            (lam aq
                                              [(lam ar
                                                  (case [b ar] [(lam as
                                                        (case [b as] (error)
                                                          [(builtin unBData) [c
                                                              [e as]]]))
                                                      [(builtin unConstrData) [c
                                                          [e
                                                            [(builtin unConstrData)
                                                              [c [e
                                                                  [(builtin unConstrData)
                                                                    [c [f [e
                                                                          [(builtin unConstrData)
                                                                            [c
                                                                              [e
                                                                                ar]]]]]]]]]]]]]]
                                                    (error)))
                                                [(builtin unConstrData) [(lam at
                                                      (lam au
                                                        [h at [(lam av
                                                              (lam aw
                                                                [(builtin equalsData)
                                                                  [c [e
                                                                      [(builtin unConstrData)
                                                                        aw]]]
                                                                  av]))
                                                            [(builtin constrData)
                                                              (con integer 0)
                                                              au]]]))
                                                    [(builtin unListData) [c
                                                        ap]] aq]]]))]) (lam ax
                                        (lam ay
                                          [(lam az
                                              (lam ba
                                                (case (constr 0 az
                                                    (con data (I 0)) (lam bb
                                                      [(lam bc
                                                          (lam bd
                                                            [(builtin iData)
                                                              (case [ba bd] bc
                                                                [(builtin addInteger)
                                                                  bc
                                                                  (con integer 1)])]))
                                                        [(builtin unIData)
                                                          bb]])) k)))
                                            [(builtin unListData) [c ax]]
                                            (lam be
                                              [(lam bf
                                                  (case [b bf] (con bool False)
                                                    [(builtin equalsByteString)
                                                      [(builtin unBData) [c [e
                                                            bf]]] ay]))
                                                [(builtin unConstrData) [c [e
                                                      [(builtin unConstrData) [c
                                                          [e
                                                            [(builtin unConstrData)
                                                              [c [f [e
                                                                    [(builtin unConstrData)
                                                                      be]]]]]]]]]]]])]))])
                                  [g (lam k
                                      (lam bg
                                        (lam bh
                                          (lam bi
                                            (case bg (lam bj
                                                (lam bk
                                                  (case (constr 0 bk [bi bh bj]
                                                      bi) k))) bh)))))]])
                              (lam bl
                                [(lam bm
                                    (case [b bm] [(builtin unBData) [c [e bm]]]
                                      (error))) [(builtin unConstrData) [c
                                      bl]]])]) (lam bn
                            (lam bo
                              (case (constr 0 [(builtin unListData) [c [a
                                        (con integer 8) bn]]] [(builtin bData)
                                    bo] (lam bp
                                    [(lam bq
                                        (lam br
                                          [(builtin equalsByteString) bq
                                            [(builtin unBData) br]]))
                                      [(builtin unBData) bp]])) (lam bs
                                  (lam bt
                                    (lam bu
                                      (case (case [b [(builtin unConstrData) [h
                                                bs (lam bv
                                                  [(builtin equalsData) bv
                                                    bt])]]] (con bool False)
                                          (con bool True)) (con bool True)
                                        (con bool False))))))))]) [g (lam h
                          (lam bw
                            (lam bx
                              (case bw (lam by
                                  (lam bz
                                    (case [bx by] [h bz bx]
                                      [(builtin constrData) (con integer 0) [d
                                          by (con (list data) [])]])))
                                (con data (Constr 1 []))))))]]) (lam ca
                    [(lam cb [ca (lam cc [cb cb cc])]) (lam cb
                        [ca (lam cc [cb cb cc])])])]))))))))