(program 1.1.0 (case (constr 0 (force (force (builtin chooseList)))
      (force (force (builtin fstPair))) (force (builtin headList))
      (force (builtin ifThenElse)) (force (builtin mkCons))
      (force (force (builtin sndPair))) (force (builtin tailList))
      (force (builtin trace))) (lam a
      (lam b
        (lam c
          (lam d
            (lam e
              (lam f
                (lam g
                  (lam h
                    [(lam i
                        [(lam j
                            [(lam k
                                [(lam l
                                    [(lam m
                                        [(lam n
                                            [(lam o
                                                (lam p
                                                  [(lam q
                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                            [b q]
                                                            (con integer 1)]
                                                          (delay [(lam r
                                                              [(lam s
                                                                  [(lam t
                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                            [b
                                                                              t]
                                                                            (con integer 0)]
                                                                          (delay (case (constr 0 [f
                                                                                [(builtin unConstrData)
                                                                                  [c
                                                                                    [f
                                                                                      [(builtin unConstrData)
                                                                                        p]]]]]
                                                                              [f
                                                                                [(builtin unConstrData)
                                                                                  [c
                                                                                    r]]]
                                                                              s
                                                                              [(builtin unBData)
                                                                                [c
                                                                                  [f
                                                                                    t]]]) (lam u
                                                                              (lam v
                                                                                (lam w
                                                                                  (lam x
                                                                                    [(lam y
                                                                                        [(lam z
                                                                                            [(lam aa
                                                                                                (force (case (constr 0 [(builtin equalsInteger)
                                                                                                      [n
                                                                                                        u
                                                                                                        [o
                                                                                                          u
                                                                                                          v]]
                                                                                                      (con integer 1)]
                                                                                                    (delay (con unit ()))
                                                                                                    (delay (force [h
                                                                                                      (con string "Double satisfaction")
                                                                                                      (delay (error))]))) d)))
                                                                                              (force (case (constr 0 [(builtin lessThanInteger)
                                                                                                    [(lam ab
                                                                                                        [(lam ac
                                                                                                            (force (case (constr 0 [(builtin equalsInteger)
                                                                                                                  [b
                                                                                                                    ac]
                                                                                                                  (con integer 1)]
                                                                                                                (delay [(lam ad
                                                                                                                    (force (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                                                                                              [b
                                                                                                                                [(builtin unConstrData)
                                                                                                                                  [c
                                                                                                                                    [g
                                                                                                                                      [f
                                                                                                                                        [(builtin unConstrData)
                                                                                                                                          [c
                                                                                                                                            [g
                                                                                                                                              ab]]]]]]]]
                                                                                                                              (con integer 0)]
                                                                                                                            (con bool False)
                                                                                                                            (con bool True)) d)
                                                                                                                        (delay [(builtin unIData)
                                                                                                                          [c
                                                                                                                            ad]])
                                                                                                                        (delay [(builtin subtractInteger)
                                                                                                                          [(builtin unIData)
                                                                                                                            [c
                                                                                                                              ad]]
                                                                                                                          (con integer 1)])) d)))
                                                                                                                  [f
                                                                                                                    ac]])
                                                                                                                (delay (force [h
                                                                                                                  (con string "Claim requires a finite upper bound")
                                                                                                                  (delay (error))]))) d)))
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              [f
                                                                                                                [(builtin unConstrData)
                                                                                                                  [c
                                                                                                                    [g
                                                                                                                      ab]]]]]]])
                                                                                                      [f
                                                                                                        [(builtin unConstrData)
                                                                                                          [c
                                                                                                            [g
                                                                                                              [g
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    [g
                                                                                                                      [g
                                                                                                                        [g
                                                                                                                          u]]]]]]]]]]]
                                                                                                    [(builtin unIData)
                                                                                                      [c
                                                                                                        [g
                                                                                                          [g
                                                                                                            [g
                                                                                                              w]]]]]]
                                                                                                  (delay (con unit ()))
                                                                                                  (delay (force [h
                                                                                                    (con string "Claim not permitted at or after timeout")
                                                                                                    (delay (error))]))) d))])
                                                                                          (force (case (constr 0 [k
                                                                                                u
                                                                                                [l
                                                                                                  [f
                                                                                                    [(builtin unConstrData)
                                                                                                      [c
                                                                                                        [g
                                                                                                          w]]]]]]
                                                                                              (delay (con unit ()))
                                                                                              (delay (force [h
                                                                                                (con string "Missing recipient signature")
                                                                                                (delay (error))]))) d))])
                                                                                      (force (case (constr 0 [(builtin equalsByteString)
                                                                                            [(builtin sha2_256)
                                                                                              x]
                                                                                            [(builtin unBData)
                                                                                              [c
                                                                                                [g
                                                                                                  [g
                                                                                                    w]]]]]
                                                                                          (delay (con unit ()))
                                                                                          (delay (force [h
                                                                                            (con string "Preimage does not match stored hash")
                                                                                            (delay (error))]))) d))]))))))
                                                                          (delay (case (constr 0 [f
                                                                                [(builtin unConstrData)
                                                                                  [c
                                                                                    [f
                                                                                      [(builtin unConstrData)
                                                                                        p]]]]]
                                                                              [f
                                                                                [(builtin unConstrData)
                                                                                  [c
                                                                                    r]]]
                                                                              s) (lam ae
                                                                              (lam af
                                                                                (lam ag
                                                                                  [(lam ah
                                                                                      [(lam ai
                                                                                          (force (case (constr 0 [(builtin equalsInteger)
                                                                                                [n
                                                                                                  ae
                                                                                                  [o
                                                                                                    ae
                                                                                                    af]]
                                                                                                (con integer 1)]
                                                                                              (delay (con unit ()))
                                                                                              (delay (force [h
                                                                                                (con string "Double satisfaction")
                                                                                                (delay (error))]))) d)))
                                                                                        (force (case (constr 0 [(builtin lessThanInteger)
                                                                                              [(builtin unIData)
                                                                                                [c
                                                                                                  [g
                                                                                                    [g
                                                                                                      [g
                                                                                                        ag]]]]]
                                                                                              [(lam aj
                                                                                                  [(lam ak
                                                                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                                                                            [b
                                                                                                              ak]
                                                                                                            (con integer 1)]
                                                                                                          (delay [(lam al
                                                                                                              (force (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                                                                                        [b
                                                                                                                          [(builtin unConstrData)
                                                                                                                            [c
                                                                                                                              [g
                                                                                                                                [f
                                                                                                                                  [(builtin unConstrData)
                                                                                                                                    [c
                                                                                                                                      aj]]]]]]]
                                                                                                                        (con integer 0)]
                                                                                                                      (con bool False)
                                                                                                                      (con bool True)) d)
                                                                                                                  (delay [(builtin unIData)
                                                                                                                    [c
                                                                                                                      al]])
                                                                                                                  (delay [(builtin addInteger)
                                                                                                                    [(builtin unIData)
                                                                                                                      [c
                                                                                                                        al]]
                                                                                                                    (con integer 1)])) d)))
                                                                                                            [f
                                                                                                              ak]])
                                                                                                          (delay (force [h
                                                                                                            (con string "Refund requires a finite lower bound")
                                                                                                            (delay (error))]))) d)))
                                                                                                    [(builtin unConstrData)
                                                                                                      [c
                                                                                                        [f
                                                                                                          [(builtin unConstrData)
                                                                                                            [c
                                                                                                              aj]]]]]])
                                                                                                [f
                                                                                                  [(builtin unConstrData)
                                                                                                    [c
                                                                                                      [g
                                                                                                        [g
                                                                                                          [g
                                                                                                            [g
                                                                                                              [g
                                                                                                                [g
                                                                                                                  [g
                                                                                                                    ae]]]]]]]]]]]]
                                                                                            (delay (con unit ()))
                                                                                            (delay (force [h
                                                                                              (con string "Refund not permitted at or before timeout")
                                                                                              (delay (error))]))) d))])
                                                                                    (force (case (constr 0 [k
                                                                                          ae
                                                                                          [l
                                                                                            [f
                                                                                              [(builtin unConstrData)
                                                                                                [c
                                                                                                  ag]]]]]
                                                                                        (delay (con unit ()))
                                                                                        (delay (force [h
                                                                                          (con string "Missing payer signature")
                                                                                          (delay (error))]))) d))])))))) d)))
                                                                    [(builtin unConstrData)
                                                                      [c [g [f
                                                                            [(builtin unConstrData)
                                                                              p]]]]]])
                                                                [(lam am
                                                                    [(lam an
                                                                        (force (case (constr 0 [(builtin equalsInteger)
                                                                              [b
                                                                                am]
                                                                              (con integer 0)]
                                                                            (delay [f
                                                                              [(builtin unConstrData)
                                                                                [c
                                                                                  [f
                                                                                    am]]]])
                                                                            (delay (force [h
                                                                              (con string "Missing HTLC datum")
                                                                              (delay (error))]))) d)))
                                                                      [g r]])
                                                                  [(builtin unConstrData)
                                                                    [c [g
                                                                        r]]]]])
                                                            [f q]])
                                                          (delay (force [h
                                                            (con string "Expected SpendingScript")
                                                            (delay (error))]))) d)))
                                                    [(builtin unConstrData) [c
                                                        [g [g [f
                                                              [(builtin unConstrData)
                                                                p]]]]]]]))
                                              (lam ao
                                                (lam ap
                                                  [(lam aq
                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                            [b aq]
                                                            (con integer 0)]
                                                          (delay [(lam ar
                                                              (force (case (constr 0 [(builtin equalsInteger)
                                                                    [b ar]
                                                                    (con integer 1)]
                                                                  (delay [(builtin unBData)
                                                                    [c [f ar]]])
                                                                  (delay (force [h
                                                                    (con string "Expected ScriptCredential")
                                                                    (delay (error))]))) d)))
                                                            [(builtin unConstrData)
                                                              [c [f
                                                                  [(builtin unConstrData)
                                                                    [c [f
                                                                        [(builtin unConstrData)
                                                                          [c [g
                                                                              [f
                                                                                [(builtin unConstrData)
                                                                                  [c
                                                                                    [f
                                                                                      aq]]]]]]]]]]]]]])
                                                          (delay (force [h
                                                            (con string "Own input not found")
                                                            (delay (error))]))) d)))
                                                    [(builtin unConstrData)
                                                      [(lam as
                                                          (lam at
                                                            [j as (lam au
                                                                [(lam av
                                                                    (lam aw
                                                                      (force (case (constr 0 [(builtin equalsByteString)
                                                                            [(builtin unBData)
                                                                              [c
                                                                                av]]
                                                                            [(builtin unBData)
                                                                              [c
                                                                                aw]]]
                                                                          (delay [(builtin equalsInteger)
                                                                            [(builtin unIData)
                                                                              [c
                                                                                [g
                                                                                  av]]]
                                                                            [(builtin unIData)
                                                                              [c
                                                                                [g
                                                                                  aw]]]])
                                                                          (delay (con bool False))) d))))
                                                                  [f
                                                                    [(builtin unConstrData)
                                                                      [c [f
                                                                          [(builtin unConstrData)
                                                                            au]]]]]
                                                                  at])]))
                                                        [(builtin unListData) [c
                                                            ao]] ap]]]))])
                                          (lam ax
                                            (lam ay
                                              [(lam az
                                                  (lam ba
                                                    [(builtin unIData)
                                                      (case (constr 0 az
                                                          (con data (I 0))
                                                          (lam bb
                                                            (lam bc
                                                              [(lam bd
                                                                  (lam be
                                                                    [(builtin iData)
                                                                      (force (case (constr 0 [ba
                                                                            be]
                                                                          (delay [(builtin addInteger)
                                                                            bd
                                                                            (con integer 1)])
                                                                          (delay bd)) d))]))
                                                                [(builtin unIData)
                                                                  bb]
                                                                bc]))) m)]))
                                                [(builtin unListData) [c ax]]
                                                (lam bf
                                                  [(lam bg
                                                      (force (case (constr 0 [(builtin equalsInteger)
                                                            [b bg]
                                                            (con integer 1)]
                                                          (delay [(builtin equalsByteString)
                                                            [(builtin unBData)
                                                              [c [f bg]]] ay])
                                                          (delay (con bool False))) d)))
                                                    [(builtin unConstrData) [c
                                                        [f
                                                          [(builtin unConstrData)
                                                            [c [f
                                                                [(builtin unConstrData)
                                                                  [c [g [f
                                                                        [(builtin unConstrData)
                                                                          bf]]]]]]]]]]]])]))])
                                      [i (lam m
                                          (lam bh
                                            (lam bi
                                              (lam bj
                                                (force (case (constr 0 bh
                                                    (delay bi) (delay [(lam bk
                                                        [(lam bl
                                                            (lam bm
                                                              [(lam bn
                                                                  (lam bo
                                                                    (case (constr 0 bk
                                                                        bn
                                                                        bo) m)))
                                                                [bj bi bl] bm]))
                                                          [c bh]]) [g bh]
                                                      bj])) a))))))]]) (lam bp
                                    [(lam bq
                                        (force (case (constr 0 [(builtin equalsInteger)
                                              [b bq] (con integer 0)]
                                            (delay [(builtin unBData) [c [f
                                                  bq]]]) (delay (force [h
                                              (con string "Expected PubKeyCredential")
                                              (delay (error))]))) d)))
                                      [(builtin unConstrData) [c bp]]])])
                              (lam br
                                (lam bs
                                  [(lam bt
                                      (lam bu
                                        (case (constr 0 [(builtin unListData) [c
                                                [g [g [g [g [g [g [g [g
                                                                br]]]]]]]]]] bt
                                            (lam bv
                                              [(lam bw
                                                  (lam bx
                                                    [bu bw [(builtin unBData)
                                                        bx]]))
                                                [(builtin unBData)
                                                  bv]])) (lam by
                                            (lam bz
                                              (lam ca
                                                (case (constr 0 (case (constr 0 [(builtin equalsInteger)
                                                          [b
                                                            [(builtin unConstrData)
                                                              [j by (lam cb
                                                                  [ca cb bz])]]]
                                                          (con integer 0)]
                                                        (con bool False)
                                                        (con bool True)) d)
                                                    (con bool False)
                                                    (con bool True)) d)))))))
                                    [(builtin bData) bs]
                                    (builtin equalsByteString)]))]) [i (lam j
                              (lam cc
                                (lam cd
                                  (force (case (constr 0 cc
                                      (delay (con data (Constr 1 [])))
                                      (delay (force (case (constr 0 [cd [c cc]]
                                          (delay [(builtin constrData)
                                            (con integer 0) [e [c cc]
                                              (con (list data) [])]])
                                          (delay [(lam ce (lam cf [j ce cf])) [g
                                              cc] cd])) d)))) a)))))]]) (lam cg
                        [(lam ch [cg (lam ci [ch ch ci])]) (lam ch
                            [cg (lam ci [ch ch ci])])])]))))))))))